# step1.yml
name: dev branch auto ci

on:
  push:
    branches: [ step1 ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/gavi-shopping-cart/build/libs
            ./run.sh